## Building a dataset
The goal of this notebook is to scrap tweets from twitter in order to bild a suitable dataset to classify SDG related tweets.

In [ ]:
# IMPORTS
import tweepy
import os
import requests
import json
import pandas as pd
import csv
import time
import dateutil

In [ ]:
# set bearer token as an enviroment variable (The set token is an academic token)
os.environ['TOKEN_ACADEMIC'] = 'INSERT YOUR ACADEMIC TOKEN'

In [ ]:
# functions

# retrieve the token from the environemtn variable to be used bu the app
def auth():
    return os.getenv('TOKEN_ACADEMIC')

# create heathers
# sets the heathers for a future request to the twitter api
def create_headers(bearer_token):
    headers = {"Authorization": "Bearer {}".format(bearer_token)}
    return headers

#create url
def create_url_search_archive(keyword, start_date, end_date, max_results = 10): #start_date, end_date, 
    
    # set the api endpoint to archive (all)
    search_url = "https://api.twitter.com/2/tweets/search/all"
    
    #change params based on the endpoint you are using
    query_params = {'query': keyword,
                    'start_time': start_date,
                    'end_time': end_date,
                    'max_results': max_results,
                    'tweet.fields': 'id,text,author_id,created_at,lang,public_metrics',
                    'next_token': {}}
    return (search_url, query_params)

#connect to the endpoint
def connect_to_endpoint(url, headers, params, next_token = None, silent=False):
    params['next_token'] = next_token   #params object received from create_url function
    response = requests.request("GET", url, headers = headers, params = params)
    if not silent:
        print("Endpoint Response Code: " + str(response.status_code))
    if response.status_code != 200:
        raise Exception(response.status_code, response.text)
    return response.json()

### Build the query

For more information on how to build queries for the twitter API refer to the twitter API documentation.\
NOTE: In later archive searches we have been using the twitter no-code API tool for academic users.

Query log:\
'#SDGs lang:en -is:retweet'

In [ ]:
# function calls
#Inputs for the request
bearer_token = auth()
headers = create_headers(bearer_token)
keyword_eng = '#SDGs lang:en -is:retweet'
start_time = "2015-09-01T00:00:00.000Z" # UN sustainable development summit (sept 2015) SDGs are set for 2030
end_time = "2018-08-10T12:18:23.000Z" # ADAPT to build in different datasets

# predefined time is last week
max_results = 500 # we know by tweet count exploration that only exist about 1.5M (500 is max one can get)
next_token = None

#url_eng = create_url_search_recent(keyword_eng, max_results)#start_time,end_time,
url_eng, query_params_eng = create_url_search_archive(keyword_eng, start_time, end_time, max_results)

# Set the storage parameters:
filename='tweetsSDG_en5.csv' # ADAPT TO BUILD DATASET
field_heathers=['twid','authid','created_at','lang','like_count','quote_count','reply_count','retweet_count','text']

### Call twitter API
Use the built query to retrieve data from tweets and store it in a csv file.

In [ ]:
# Create and open file to store tweet rows + define heathers
csvFile = open(filename, "w", newline="", encoding='utf-8')
csvWriter = csv.writer(csvFile)
csvWriter.writerow(field_heathers)

counter = 0

while True:
    json_response = connect_to_endpoint(url_eng, headers, query_params_eng, next_token, silent=True)
    time.sleep(2) # To avoid spamming the API

    #Loop through each tweet
    for tweet in json_response['data']:

        fields=[tweet['id'],
                tweet['author_id'],
                dateutil.parser.parse(tweet['created_at']),
                tweet['lang'],
                tweet['public_metrics']['like_count'],
                tweet['public_metrics']['quote_count'],
                tweet['public_metrics']['reply_count'],
                tweet['public_metrics']['retweet_count'],
                tweet['text']]

        # Append the result to the CSV file
        csvWriter.writerow(fields)
        counter += 1
    print("Total # of Tweets added: ", counter)
    
    if 'next_token' in json_response['meta']:
        next_token = json_response['meta']['next_token']
    else:
        print('Total tweets stored: ', counter)
        break
csvFile.close()

Total # of Tweets added:  500
Total # of Tweets added:  992
Total # of Tweets added:  1489
Total # of Tweets added:  1989
Total # of Tweets added:  2482
Total # of Tweets added:  2980
Total # of Tweets added:  3476
Total # of Tweets added:  3972
Total # of Tweets added:  4467
Total # of Tweets added:  4962
Total # of Tweets added:  5456
Total # of Tweets added:  5954
Total # of Tweets added:  6451
Total # of Tweets added:  6950
Total # of Tweets added:  7446
Total # of Tweets added:  7944
Total # of Tweets added:  8442
Total # of Tweets added:  8941
Total # of Tweets added:  9439
Total # of Tweets added:  9938
Total # of Tweets added:  10430
Total # of Tweets added:  10927
Total # of Tweets added:  11420
Total # of Tweets added:  11916
Total # of Tweets added:  12414
Total # of Tweets added:  12913
Total # of Tweets added:  13409
Total # of Tweets added:  13908
Total # of Tweets added:  14406
Total # of Tweets added:  14903
Total # of Tweets added:  15403
Total # of Tweets added:  15902
Total # of Tweets added:  16401
Total # of Tweets added:  16889
Total # of Tweets added:  17388
Total # of Tweets added:  17884
Total # of Tweets added:  18382
Total # of Tweets added:  18880
Total # of Tweets added:  19377
Total # of Tweets added:  19872
Total # of Tweets added:  20367
Total # of Tweets added:  20863
Total # of Tweets added:  21358
Total # of Tweets added:  21856
Total # of Tweets added:  22353
Total # of Tweets added:  22853
Total # of Tweets added:  23349
Total # of Tweets added:  23848
Total # of Tweets added:  24347
Total # of Tweets added:  24845
Total # of Tweets added:  25343
Total # of Tweets added:  25838
Total # of Tweets added:  26336
Total # of Tweets added:  26834
Total # of Tweets added:  27330
Total # of Tweets added:  27821
Total # of Tweets added:  28320
Total # of Tweets added:  28819
Total # of Tweets added:  29315
Total # of Tweets added:  29808
Total # of Tweets added:  30306
Total # of Tweets added:  30798
Total # of Tweets added:  31292
Total # of Tweets added:  31790
Total # of Tweets added:  32290
Total # of Tweets added:  32790
Total # of Tweets added:  33287
Total # of Tweets added:  33783
Total # of Tweets added:  34276
Total # of Tweets added:  34770
Total # of Tweets added:  35263
Total # of Tweets added:  35753
Total # of Tweets added:  36250
Total # of Tweets added:  36748
Total # of Tweets added:  37239
Total # of Tweets added:  37728
Total # of Tweets added:  38226
Total # of Tweets added:  38716
Total # of Tweets added:  39206
Total # of Tweets added:  39704
Total # of Tweets added:  40193
Total # of Tweets added:  40692
Total # of Tweets added:  41192
Total # of Tweets added:  41689
Total # of Tweets added:  42187
Total # of Tweets added:  42685
Total # of Tweets added:  43184
Total # of Tweets added:  43683
Total # of Tweets added:  44179
Total # of Tweets added:  44668
Total # of Tweets added:  45166
Total # of Tweets added:  45665
Total # of Tweets added:  46162
Total # of Tweets added:  46655
Total # of Tweets added:  47151
Total # of Tweets added:  47648
Total # of Tweets added:  48144
Total # of Tweets added:  48641
Total # of Tweets added:  49139
Total # of Tweets added:  49636
Total # of Tweets added:  50131
Total # of Tweets added:  50623
Total # of Tweets added:  51121
Total # of Tweets added:  51618
Total # of Tweets added:  52117
Total # of Tweets added:  52617
Total # of Tweets added:  53116
Total # of Tweets added:  53612
Total # of Tweets added:  54111
Total # of Tweets added:  54611
Total # of Tweets added:  55109
Total # of Tweets added:  55608
Total # of Tweets added:  56107
Total # of Tweets added:  56605
Total # of Tweets added:  57105
Total # of Tweets added:  57603
Total # of Tweets added:  58102
Total # of Tweets added:  58602
Total # of Tweets added:  59095
Total # of Tweets added:  59592
Total # of Tweets added:  60089
Total # of Tweets added:  60588
Total # of Tweets added:  61086
Total # of Tweets added:  61585
Total # of Tweets added:  62082
Total # of Tweets added:  62581
Total # of Tweets added:  63081
Total # of Tweets added:  63581
Total # of Tweets added:  64081
Total # of Tweets added:  64579
Total # of Tweets added:  65079
Total # of Tweets added:  65578
Total # of Tweets added:  66078
Total # of Tweets added:  66578
Total # of Tweets added:  67078
Total # of Tweets added:  67573
Total # of Tweets added:  68073
Total # of Tweets added:  68570
Total # of Tweets added:  69069
Total # of Tweets added:  69568
Total # of Tweets added:  70065
Total # of Tweets added:  70564
Total # of Tweets added:  71063
Total # of Tweets added:  71558
Total # of Tweets added:  72056
Total # of Tweets added:  72552
Total # of Tweets added:  73051
Total # of Tweets added:  73550
Total # of Tweets added:  74050
Total # of Tweets added:  74549
Total # of Tweets added:  75044
Total # of Tweets added:  75542
Total # of Tweets added:  76041
Total # of Tweets added:  76539
Total # of Tweets added:  77038
Total # of Tweets added:  77538
Total # of Tweets added:  78038
Total # of Tweets added:  78538
Total # of Tweets added:  79037
Total # of Tweets added:  79533
Total # of Tweets added:  80032
Total # of Tweets added:  80531
Total # of Tweets added:  81017
Total # of Tweets added:  81515
Total # of Tweets added:  82012
Total # of Tweets added:  82511
Total # of Tweets added:  83008
Total # of Tweets added:  83506
Total # of Tweets added:  84003
Total # of Tweets added:  84503
Total # of Tweets added:  84999
Total # of Tweets added:  85498
Total # of Tweets added:  85995
Total # of Tweets added:  86489
Total # of Tweets added:  86981
Total # of Tweets added:  87481
Total # of Tweets added:  87981
Total # of Tweets added:  88480
Total # of Tweets added:  88979
Total # of Tweets added:  89478
Total # of Tweets added:  89972
Total # of Tweets added:  90470
Total # of Tweets added:  90967
Total # of Tweets added:  91467
Total # of Tweets added:  91966
Total # of Tweets added:  92464
Total # of Tweets added:  92963
Total # of Tweets added:  93463
Total # of Tweets added:  93963
Total # of Tweets added:  94460
Total # of Tweets added:  94934
Total # of Tweets added:  95421
Total # of Tweets added:  95918
Total # of Tweets added:  96408
Total # of Tweets added:  96904
Total # of Tweets added:  97399
Total # of Tweets added:  97899
Total # of Tweets added:  98399
Total # of Tweets added:  98896
Total # of Tweets added:  99394
Total # of Tweets added:  99894
Total # of Tweets added:  100393
Total # of Tweets added:  100891
Total # of Tweets added:  101389
Total # of Tweets added:  101889
Total # of Tweets added:  102388
Total # of Tweets added:  102887
Total # of Tweets added:  103386
Total # of Tweets added:  103884
Total # of Tweets added:  104384
Total # of Tweets added:  104884
Total # of Tweets added:  105384
Total # of Tweets added:  105881
Total # of Tweets added:  106381
Total # of Tweets added:  106881
Total # of Tweets added:  107380
Total # of Tweets added:  107878
Total # of Tweets added:  108376
Total # of Tweets added:  108871
Total # of Tweets added:  109371
Total # of Tweets added:  109867
Total # of Tweets added:  110361
Total # of Tweets added:  110860
Total # of Tweets added:  111342
Total # of Tweets added:  111841
Total # of Tweets added:  112340
Total # of Tweets added:  112838
Total # of Tweets added:  113333
Total # of Tweets added:  113830
Total # of Tweets added:  114330
Total # of Tweets added:  114830
Total # of Tweets added:  115329
Total # of Tweets added:  115828
Total # of Tweets added:  116328
Total # of Tweets added:  116823
Total # of Tweets added:  117316
Total # of Tweets added:  117813
Total # of Tweets added:  118309
Total # of Tweets added:  118808
Total # of Tweets added:  119306
Total # of Tweets added:  119804
Total # of Tweets added:  120304
Total # of Tweets added:  120802
Total # of Tweets added:  121298
Total # of Tweets added:  121797
Total # of Tweets added:  122295
Total # of Tweets added:  122793
Total # of Tweets added:  123290
Total # of Tweets added:  123789
Total # of Tweets added:  124284
Total # of Tweets added:  124778
Total # of Tweets added:  125275
Total # of Tweets added:  125774
Total # of Tweets added:  126271
Total # of Tweets added:  126768
Total # of Tweets added:  127264

Total # of Tweets added:  127764
Total # of Tweets added:  128264
Total # of Tweets added:  128762
Total # of Tweets added:  129259
Total # of Tweets added:  129757
Total # of Tweets added:  130254
Total # of Tweets added:  130750
Total # of Tweets added:  131250
Total # of Tweets added:  131747
Total # of Tweets added:  132244
Total # of Tweets added:  132744
Total # of Tweets added:  133244
Total # of Tweets added:  133740
Total # of Tweets added:  134234
Total # of Tweets added:  134732
Total # of Tweets added:  135232
Total # of Tweets added:  135726
Total # of Tweets added:  136226
Total # of Tweets added:  136722
Total # of Tweets added:  137221
Total # of Tweets added:  137721
Total # of Tweets added:  138218
Total # of Tweets added:  138712
Total # of Tweets added:  139211
Total # of Tweets added:  139708
Total # of Tweets added:  140207
Total # of Tweets added:  140704
Total # of Tweets added:  141200
Total # of Tweets added:  141696
Total # of Tweets added:  142195
Total # of Tweets added:  142691
Total # of Tweets added:  143190
Total # of Tweets added:  143690
Total # of Tweets added:  144187
Total # of Tweets added:  144685
Total # of Tweets added:  145184
Total # of Tweets added:  145683
Total # of Tweets added:  146179
Total # of Tweets added:  146675
Total # of Tweets added:  147174
Total # of Tweets added:  147670
Total # of Tweets added:  148168
Total # of Tweets added:  148666
Total # of Tweets added:  149162
Total # of Tweets added:  149658
Total # of Tweets added:  150155
Total # of Tweets added:  150654
Total # of Tweets added:  151154
Total # of Tweets added:  151651
Total # of Tweets added:  152146
Total # of Tweets added:  152643
Total # of Tweets added:  153138
Total # of Tweets added:  153633
Total # of Tweets added:  154129
Total # of Tweets added:  154627
Total # of Tweets added:  155121
Total # of Tweets added:  155620
Total # of Tweets added:  156119
Total # of Tweets added:  156618
Total # of Tweets added:  157118
Total # of Tweets added:  157616
Total # of Tweets added:  158116
Total # of Tweets added:  158613
Total # of Tweets added:  159111
Total # of Tweets added:  159609
Total # of Tweets added:  160107
Total # of Tweets added:  160603
Total # of Tweets added:  161096
Total # of Tweets added:  161594
Total # of Tweets added:  162094
Total # of Tweets added:  162594
Total # of Tweets added:  163093
Total # of Tweets added:  163593
Total # of Tweets added:  164087
Total # of Tweets added:  164585
Total # of Tweets added:  165081
Total # of Tweets added:  165579
Total # of Tweets added:  166076
Total # of Tweets added:  166574
Total # of Tweets added:  167068
Total # of Tweets added:  167566
Total # of Tweets added:  168062
Total # of Tweets added:  168561
Total # of Tweets added:  169059
Total # of Tweets added:  169555
Total # of Tweets added:  170052
Total # of Tweets added:  170550
Total # of Tweets added:  171043
Total # of Tweets added:  171540
Total # of Tweets added:  172034
Total # of Tweets added:  172530
Total # of Tweets added:  173024
Total # of Tweets added:  173517
Total # of Tweets added:  174015
Total # of Tweets added:  174514
Total # of Tweets added:  175010
Total # of Tweets added:  175505
Total # of Tweets added:  176004
Total # of Tweets added:  176503
Total # of Tweets added:  176998
Total # of Tweets added:  177495
Total # of Tweets added:  177992
Total # of Tweets added:  178491
Total # of Tweets added:  178991
Total # of Tweets added:  179489
Total # of Tweets added:  179988
Total # of Tweets added:  180486
Total # of Tweets added:  180983
Total # of Tweets added:  181483
Total # of Tweets added:  181980
Total # of Tweets added:  182479
Total # of Tweets added:  182977
Total # of Tweets added:  183475
Total # of Tweets added:  183974
Total # of Tweets added:  184473
Total # of Tweets added:  184972
Total # of Tweets added:  185469
Total # of Tweets added:  185966
Total # of Tweets added:  186465
Total # of Tweets added:  186956
Total # of Tweets added:  187452
Total # of Tweets added:  187949
Total # of Tweets added:  188447
Total # of Tweets added:  188945
Total # of Tweets added:  189443
Total # of Tweets added:  189939
Total # of Tweets added:  190435
Total # of Tweets added:  190933
Total # of Tweets added:  191429
Total # of Tweets added:  191927
Total # of Tweets added:  192424
Total # of Tweets added:  192921
Total # of Tweets added:  193419
Total # of Tweets added:  193915
Total # of Tweets added:  194412
Total # of Tweets added:  194904
Total # of Tweets added:  195391
Total # of Tweets added:  195882
Total # of Tweets added:  196382
Total # of Tweets added:  196879
Total # of Tweets added:  197376
Total # of Tweets added:  197875
Total # of Tweets added:  198371
Total # of Tweets added:  198871
Total # of Tweets added:  199369
Total # of Tweets added:  199867
Total # of Tweets added:  200362
Total # of Tweets added:  200859
Total # of Tweets added:  201356
Total # of Tweets added:  201853
Total # of Tweets added:  202352
Total # of Tweets added:  202852
Total # of Tweets added:  203351
Total # of Tweets added:  203843
Total # of Tweets added:  204338
Total # of Tweets added:  204836
Total # of Tweets added:  205336
Total # of Tweets added:  205836
Total # of Tweets added:  206336
Total # of Tweets added:  206836
Total # of Tweets added:  207336
Total # of Tweets added:  207835
Total # of Tweets added:  208335
Total # of Tweets added:  208835
Total # of Tweets added:  209335
Total # of Tweets added:  209834
Total # of Tweets added:  210330
Total # of Tweets added:  210829
Total # of Tweets added:  211329
Total # of Tweets added:  211829
Total # of Tweets added:  212328
Total # of Tweets added:  212828
Total # of Tweets added:  213328
Total # of Tweets added:  213828
Total # of Tweets added:  214327
Total # of Tweets added:  214827
Total # of Tweets added:  215327
Total # of Tweets added:  215827
Total # of Tweets added:  216326
Total # of Tweets added:  216826
Total # of Tweets added:  217324
Total # of Tweets added:  217821
Total # of Tweets added:  218321
Total # of Tweets added:  218818
Total # of Tweets added:  219317
Total # of Tweets added:  219816
Total # of Tweets added:  220311
Total # of Tweets added:  220809
Total # of Tweets added:  221307
Total # of Tweets added:  221804
Total # of Tweets added:  222303
Total # of Tweets added:  222803
Total # of Tweets added:  223299
Total # of Tweets added:  223799
Total # of Tweets added:  224299
Total # of Tweets added:  224799
Total # of Tweets added:  225299
Total # of Tweets added:  225794
Total # of Tweets added:  226291
Total # of Tweets added:  226787
Total # of Tweets added:  227286
Total # of Tweets added:  227786
Total # of Tweets added:  228283
Total # of Tweets added:  228783
Total # of Tweets added:  229283
Total # of Tweets added:  229781
Total # of Tweets added:  230280
Total # of Tweets added:  230775
Total # of Tweets added:  231274
Total # of Tweets added:  231773
Total # of Tweets added:  232268
Total # of Tweets added:  232768
Total # of Tweets added:  233268
Total # of Tweets added:  233764
Total # of Tweets added:  234263
Total # of Tweets added:  234762
Total # of Tweets added:  235259
Total # of Tweets added:  235756
Total # of Tweets added:  236256
Total # of Tweets added:  236755
Total # of Tweets added:  237251
Total # of Tweets added:  237747
Total # of Tweets added:  238247
Total # of Tweets added:  238746
Total # of Tweets added:  239239
Total # of Tweets added:  239738
Total # of Tweets added:  240230
Total # of Tweets added:  240727
Total # of Tweets added:  241226
Total # of Tweets added:  241724
Total # of Tweets added:  242223
Total # of Tweets added:  242723
Total # of Tweets added:  243222
Total # of Tweets added:  243717
Total # of Tweets added:  244217
Total # of Tweets added:  244717
Total # of Tweets added:  245215
Total # of Tweets added:  245714
Total # of Tweets added:  246213
Total # of Tweets added:  246713
Total # of Tweets added:  247212
Total # of Tweets added:  247712
Total # of Tweets added:  248211
Total # of Tweets added:  248710
Total # of Tweets added:  249207
Total # of Tweets added:  249706
Total # of Tweets added:  250206
Total # of Tweets added:  250706
Total # of Tweets added:  251203

Total # of Tweets added:  251703
Total # of Tweets added:  252201
Total # of Tweets added:  252699
Total # of Tweets added:  253195
Total # of Tweets added:  253695
Total # of Tweets added:  254192
Total # of Tweets added:  254691
Total # of Tweets added:  255190
Total # of Tweets added:  255687
Total # of Tweets added:  256183
Total # of Tweets added:  256679
Total # of Tweets added:  257175
Total # of Tweets added:  257674
Total # of Tweets added:  258173
Total # of Tweets added:  258671
Total # of Tweets added:  259169
Total # of Tweets added:  259669
Total # of Tweets added:  260168
Total # of Tweets added:  260666
Total # of Tweets added:  261165
Total # of Tweets added:  261663
Total # of Tweets added:  262161
Total # of Tweets added:  262658
Total # of Tweets added:  263157
Total # of Tweets added:  263657
Total # of Tweets added:  264155
Total # of Tweets added:  264652
Total # of Tweets added:  265143
Total # of Tweets added:  265639
Total # of Tweets added:  266139
Total # of Tweets added:  266635
Total # of Tweets added:  267134
Total # of Tweets added:  267625
Total # of Tweets added:  268123
Total # of Tweets added:  268622
Total # of Tweets added:  269117
Total # of Tweets added:  269611
Total # of Tweets added:  270107
Total # of Tweets added:  270602
Total # of Tweets added:  271098
Total # of Tweets added:  271594
Total # of Tweets added:  272090
Total # of Tweets added:  272582
Total # of Tweets added:  273081
Total # of Tweets added:  273581
Total # of Tweets added:  274078
Total # of Tweets added:  274576
Total # of Tweets added:  275073
Total # of Tweets added:  275561
Total # of Tweets added:  276057
Total # of Tweets added:  276551
Total # of Tweets added:  277048
Total # of Tweets added:  277544
Total # of Tweets added:  278041
Total # of Tweets added:  278535
Total # of Tweets added:  279026
Total # of Tweets added:  279522
Total # of Tweets added:  280020
Total # of Tweets added:  280515
Total # of Tweets added:  281015
Total # of Tweets added:  281515
Total # of Tweets added:  282014
Total # of Tweets added:  282507
Total # of Tweets added:  283004
Total # of Tweets added:  283502
Total # of Tweets added:  283996
Total # of Tweets added:  284496
Total # of Tweets added:  284996
Total # of Tweets added:  285495
Total # of Tweets added:  285980
Total # of Tweets added:  286480
Total # of Tweets added:  286980
Total # of Tweets added:  287479
Total # of Tweets added:  287975
Total # of Tweets added:  288474
Total # of Tweets added:  288974
Total # of Tweets added:  289451
Total # of Tweets added:  289949
Total # of Tweets added:  290448
Total # of Tweets added:  290945
Total # of Tweets added:  291444
Total # of Tweets added:  291942
Total # of Tweets added:  292442
Total # of Tweets added:  292940
Total # of Tweets added:  293438
Total # of Tweets added:  293936
Total # of Tweets added:  294435
Total # of Tweets added:  294935
Total # of Tweets added:  295435
Total # of Tweets added:  295934
Total # of Tweets added:  296432
Total # of Tweets added:  296931
Total # of Tweets added:  297431
Total # of Tweets added:  297931
Total # of Tweets added:  298427
Total # of Tweets added:  298927
Total # of Tweets added:  299426
Total # of Tweets added:  299926
Total # of Tweets added:  300423
Total # of Tweets added:  300922
Total # of Tweets added:  301419
Total # of Tweets added:  301918
Total # of Tweets added:  302413
Total # of Tweets added:  302911
Total # of Tweets added:  303410
Total # of Tweets added:  303907
Total # of Tweets added:  304402
Total # of Tweets added:  304901
Total # of Tweets added:  305401
Total # of Tweets added:  305900
Total # of Tweets added:  306399
Total # of Tweets added:  306895
Total # of Tweets added:  307394
Total # of Tweets added:  307894
Total # of Tweets added:  308389
Total # of Tweets added:  308888
Total # of Tweets added:  309388
Total # of Tweets added:  309888
Total # of Tweets added:  310387
Total # of Tweets added:  310887
Total # of Tweets added:  311377
Total # of Tweets added:  311876
Total # of Tweets added:  312376
Total # of Tweets added:  312875
Total # of Tweets added:  313372
Total # of Tweets added:  313870
Total # of Tweets added:  314368
Total # of Tweets added:  314868
Total # of Tweets added:  315368
Total # of Tweets added:  315867
Total # of Tweets added:  316367
Total # of Tweets added:  316864
Total # of Tweets added:  317357
Total # of Tweets added:  317853
Total # of Tweets added:  318353
Total # of Tweets added:  318853
Total # of Tweets added:  319353
Total # of Tweets added:  319847
Total # of Tweets added:  320345
Total # of Tweets added:  320839
Total # of Tweets added:  321339
Total # of Tweets added:  321838
Total # of Tweets added:  322328
Total # of Tweets added:  322828
Total # of Tweets added:  323328
Total # of Tweets added:  323825
Total # of Tweets added:  324319
Total # of Tweets added:  324817
Total # of Tweets added:  325313
Total # of Tweets added:  325811
Total # of Tweets added:  326300
Total # of Tweets added:  326798
Total # of Tweets added:  327296
Total # of Tweets added:  327794
Total # of Tweets added:  328294
Total # of Tweets added:  328794
Total # of Tweets added:  329291
Total # of Tweets added:  329789
Total # of Tweets added:  330285
Total # of Tweets added:  330784
Total # of Tweets added:  331283
Total # of Tweets added:  331782
Total # of Tweets added:  332281
Total # of Tweets added:  332780
Total # of Tweets added:  333278
Total # of Tweets added:  333777
Total # of Tweets added:  334274
Total # of Tweets added:  334772
Total # of Tweets added:  335269
Total # of Tweets added:  335768
Total # of Tweets added:  336266
Total # of Tweets added:  336764
Total # of Tweets added:  337264
Total # of Tweets added:  337763
Total # of Tweets added:  338255
Total # of Tweets added:  338753
Total # of Tweets added:  339248
Total # of Tweets added:  339746
Total # of Tweets added:  340245
Total # of Tweets added:  340744
Total # of Tweets added:  341242
Total # of Tweets added:  341742
Total # of Tweets added:  342241
Total # of Tweets added:  342737
Total # of Tweets added:  343237
Total # of Tweets added:  343732
Total # of Tweets added:  344228
Total # of Tweets added:  344713
Total # of Tweets added:  345203
Total # of Tweets added:  345697
Total # of Tweets added:  346190
Total # of Tweets added:  346688
Total # of Tweets added:  347184
Total # of Tweets added:  347669
Total # of Tweets added:  348160
Total # of Tweets added:  348652
Total # of Tweets added:  349145
Total # of Tweets added:  349642
Total # of Tweets added:  350134
Total # of Tweets added:  350623
Total # of Tweets added:  351117
Total # of Tweets added:  351609
Total # of Tweets added:  352103
Total # of Tweets added:  352598
Total # of Tweets added:  353093
Total # of Tweets added:  353588
Total # of Tweets added:  354085
Total # of Tweets added:  354580
Total # of Tweets added:  355076
Total # of Tweets added:  355568
Total # of Tweets added:  356064
Total # of Tweets added:  356557
Total # of Tweets added:  357053
Total # of Tweets added:  357552
Total # of Tweets added:  358050
Total # of Tweets added:  358548
Total # of Tweets added:  359044
Total # of Tweets added:  359542
Total # of Tweets added:  360039
Total # of Tweets added:  360532
Total # of Tweets added:  361028
Total # of Tweets added:  361528
Total # of Tweets added:  362027
Total # of Tweets added:  362522
Total # of Tweets added:  363019
Total # of Tweets added:  363519
Total # of Tweets added:  364016
Total # of Tweets added:  364515
Total # of Tweets added:  365014
Total # of Tweets added:  365514
Total # of Tweets added:  366013
Total # of Tweets added:  366512
Total # of Tweets added:  367009
Total # of Tweets added:  367508
Total # of Tweets added:  368003
Total # of Tweets added:  368501
Total # of Tweets added:  368998
Total # of Tweets added:  369495
Total # of Tweets added:  369990
Total # of Tweets added:  370489
Total # of Tweets added:  370987
Total # of Tweets added:  371487
Total # of Tweets added:  371983
Total # of Tweets added:  372481
Total # of Tweets added:  372973
Total # of Tweets added:  373469
Total # of Tweets added:  373968
Total # of Tweets added:  374465
Total # of Tweets added:  374965

Total # of Tweets added:  375464
Total # of Tweets added:  375959
Total # of Tweets added:  376459
Total # of Tweets added:  376959
Total # of Tweets added:  377458
Total # of Tweets added:  377955
Total # of Tweets added:  378454
Total # of Tweets added:  378947
Total # of Tweets added:  379446
Total # of Tweets added:  379944
Total # of Tweets added:  380436
Total # of Tweets added:  380933
Total # of Tweets added:  381433
Total # of Tweets added:  381930
Total # of Tweets added:  382426
Total # of Tweets added:  382924
Total # of Tweets added:  383423
Total # of Tweets added:  383921
Total # of Tweets added:  384421
Total # of Tweets added:  384921
Total # of Tweets added:  385421
Total # of Tweets added:  385919
Total # of Tweets added:  386418
Total # of Tweets added:  386913
Total # of Tweets added:  387410
Total # of Tweets added:  387900
Total # of Tweets added:  388399
Total # of Tweets added:  388896
Total # of Tweets added:  389394
Total # of Tweets added:  389893
Total # of Tweets added:  390390
Total # of Tweets added:  390890
Total # of Tweets added:  391389
Total # of Tweets added:  391887
Total # of Tweets added:  392386
Total # of Tweets added:  392880
Total # of Tweets added:  393379
Total # of Tweets added:  393871
Total # of Tweets added:  394370
Total # of Tweets added:  394862
Total # of Tweets added:  395351
Total # of Tweets added:  395845
Total # of Tweets added:  396342
Total # of Tweets added:  396839
Total # of Tweets added:  397337
Total # of Tweets added:  397837
Total # of Tweets added:  398333
Total # of Tweets added:  398830
Total # of Tweets added:  399327
Total # of Tweets added:  399824
Total # of Tweets added:  400322
Total # of Tweets added:  400818
Total # of Tweets added:  401313
Total # of Tweets added:  401813
Total # of Tweets added:  402308
Total # of Tweets added:  402807
Total # of Tweets added:  403302
Total # of Tweets added:  403799
Total # of Tweets added:  404298
Total # of Tweets added:  404793
Total # of Tweets added:  405291
Total # of Tweets added:  405785
Total # of Tweets added:  406282
Total # of Tweets added:  406776
Total # of Tweets added:  407273
Total # of Tweets added:  407768
Total # of Tweets added:  408265
Total # of Tweets added:  408760
Total # of Tweets added:  409254
Total # of Tweets added:  409747
Total # of Tweets added:  410236
Total # of Tweets added:  410732
Total # of Tweets added:  411226
Total # of Tweets added:  411724
Total # of Tweets added:  412215
Total # of Tweets added:  412710
Total # of Tweets added:  413203
Total # of Tweets added:  413692
Total # of Tweets added:  414184
Total # of Tweets added:  414674
Total # of Tweets added:  415173
Total # of Tweets added:  415673
Total # of Tweets added:  416171
Total # of Tweets added:  416667
Total # of Tweets added:  417164
Total # of Tweets added:  417663
Total # of Tweets added:  418160
Total # of Tweets added:  418659
Total # of Tweets added:  419153
Total # of Tweets added:  419651
Total # of Tweets added:  420143
Total # of Tweets added:  420640
Total # of Tweets added:  421136
Total # of Tweets added:  421630
Total # of Tweets added:  422127
Total # of Tweets added:  422624
Total # of Tweets added:  423120
Total # of Tweets added:  423612
Total # of Tweets added:  424108
Total # of Tweets added:  424605
Total # of Tweets added:  425104
Total # of Tweets added:  425598
Total # of Tweets added:  426093
Total # of Tweets added:  426588
Total # of Tweets added:  427087
Total # of Tweets added:  427586
Total # of Tweets added:  428083
Total # of Tweets added:  428573
Total # of Tweets added:  429071
Total # of Tweets added:  429567
Total # of Tweets added:  430067
Total # of Tweets added:  430562
Total # of Tweets added:  431062
Total # of Tweets added:  431561
Total # of Tweets added:  432059
Total # of Tweets added:  432557
Total # of Tweets added:  433056
Total # of Tweets added:  433551
Total # of Tweets added:  434050
Total # of Tweets added:  434547
Total # of Tweets added:  435045
Total # of Tweets added:  435539
Total # of Tweets added:  436037
Total # of Tweets added:  436535
Total # of Tweets added:  437035
Total # of Tweets added:  437534
Total # of Tweets added:  438031
Total # of Tweets added:  438530
Total # of Tweets added:  439030
Total # of Tweets added:  439530
Total # of Tweets added:  440028
Total # of Tweets added:  440527
Total # of Tweets added:  441024
Total # of Tweets added:  441523
Total # of Tweets added:  442019
Total # of Tweets added:  442518
Total # of Tweets added:  443017
Total # of Tweets added:  443512
Total # of Tweets added:  444009
Total # of Tweets added:  444506
Total # of Tweets added:  445006
Total # of Tweets added:  445506
Total # of Tweets added:  446006
Total # of Tweets added:  446503
Total # of Tweets added:  446999
Total # of Tweets added:  447496
Total # of Tweets added:  447995
Total # of Tweets added:  448490
Total # of Tweets added:  448990
Total # of Tweets added:  449490
Total # of Tweets added:  449989
Total # of Tweets added:  450489
Total # of Tweets added:  450987
Total # of Tweets added:  451484
Total # of Tweets added:  451981
Total # of Tweets added:  452480
Total # of Tweets added:  452977
Total # of Tweets added:  453471
Total # of Tweets added:  453971
Total # of Tweets added:  454468
Total # of Tweets added:  454968
Total # of Tweets added:  455465
Total # of Tweets added:  455963
Total # of Tweets added:  456458
Total # of Tweets added:  456955
Total # of Tweets added:  457451
Total # of Tweets added:  457947
Total # of Tweets added:  458445
Total # of Tweets added:  458944
Total # of Tweets added:  459440
Total # of Tweets added:  459939
Total # of Tweets added:  460438
Total # of Tweets added:  460936
Total # of Tweets added:  461434
Total # of Tweets added:  461930
Total # of Tweets added:  462426
Total # of Tweets added:  462924
Total # of Tweets added:  463423
Total # of Tweets added:  463919
Total # of Tweets added:  464418
Total # of Tweets added:  464915
Total # of Tweets added:  465413
Total # of Tweets added:  465907
Total # of Tweets added:  466405
Total # of Tweets added:  466901
Total # of Tweets added:  467401
Total # of Tweets added:  467900
Total # of Tweets added:  468399
Total # of Tweets added:  468899
Total # of Tweets added:  469399
Total # of Tweets added:  469894
Total # of Tweets added:  470388
Total # of Tweets added:  470886
Total # of Tweets added:  471383
Total # of Tweets added:  471882
Total # of Tweets added:  472382
Total # of Tweets added:  472880
Total # of Tweets added:  473377
Total # of Tweets added:  473874
Total # of Tweets added:  474367
Total # of Tweets added:  474865
Total # of Tweets added:  475362
Total # of Tweets added:  475861
Total # of Tweets added:  476360
Total # of Tweets added:  476858
Total # of Tweets added:  477354
Total # of Tweets added:  477853
Total # of Tweets added:  478353
Total # of Tweets added:  478849
Total # of Tweets added:  479345
Total # of Tweets added:  479837
Total # of Tweets added:  480335
Total # of Tweets added:  480834
Total # of Tweets added:  481331
Total # of Tweets added:  481831
Total # of Tweets added:  482327
Total # of Tweets added:  482825
Total # of Tweets added:  483320
Total # of Tweets added:  483817
Total # of Tweets added:  484314
Total # of Tweets added:  484810
Total # of Tweets added:  485306
Total # of Tweets added:  485801
Total # of Tweets added:  486297
Total # of Tweets added:  486793
Total # of Tweets added:  487291
Total # of Tweets added:  487791
Total # of Tweets added:  488291
Total # of Tweets added:  488791
Total # of Tweets added:  489288
Total # of Tweets added:  489787
Total # of Tweets added:  490284
Total # of Tweets added:  490784
Total # of Tweets added:  491283
Total # of Tweets added:  491780
Total # of Tweets added:  492279
Total # of Tweets added:  492777
Total # of Tweets added:  493269
Total # of Tweets added:  493768
Total # of Tweets added:  494267
Total # of Tweets added:  494764
Total # of Tweets added:  495263
Total # of Tweets added:  495760
Total # of Tweets added:  496259
Total # of Tweets added:  496753
Total # of Tweets added:  497253
Total # of Tweets added:  497752
Total # of Tweets added:  498248
Total # of Tweets added:  498745

Total # of Tweets added:  499240
Total # of Tweets added:  499730
Total # of Tweets added:  500224
Total # of Tweets added:  500720
Total # of Tweets added:  501212
Total # of Tweets added:  501704
Total # of Tweets added:  502200
Total # of Tweets added:  502698
Total # of Tweets added:  503197
Total # of Tweets added:  503695
Total # of Tweets added:  504193
Total # of Tweets added:  504693
Total # of Tweets added:  505190
Total # of Tweets added:  505689
Total # of Tweets added:  506188
Total # of Tweets added:  506687
Total # of Tweets added:  507186
Total # of Tweets added:  507685
Total # of Tweets added:  508185
Total # of Tweets added:  508684
Total # of Tweets added:  509184
Total # of Tweets added:  509684
Total # of Tweets added:  510183
Total # of Tweets added:  510683
Total # of Tweets added:  511183
Total # of Tweets added:  511683
Total # of Tweets added:  512180
Total # of Tweets added:  512680
Total # of Tweets added:  513180
Total # of Tweets added:  513679
Total # of Tweets added:  514178
Total # of Tweets added:  514678
Total # of Tweets added:  515177
Total # of Tweets added:  515677
Total # of Tweets added:  516174
Total # of Tweets added:  516671
Total # of Tweets added:  517170
Total # of Tweets added:  517669
Total # of Tweets added:  518168
Total # of Tweets added:  518667
Total # of Tweets added:  519167
Total # of Tweets added:  519667
Total # of Tweets added:  520167
Total # of Tweets added:  520666
Total # of Tweets added:  521164
Total # of Tweets added:  521663
Total # of Tweets added:  522163
Total # of Tweets added:  522662
Total # of Tweets added:  523162
Total # of Tweets added:  523660
Total # of Tweets added:  524159
Total # of Tweets added:  524659
Total # of Tweets added:  525158
Total # of Tweets added:  525658
Total # of Tweets added:  526158
Total # of Tweets added:  526656
Total # of Tweets added:  527155
Total # of Tweets added:  527655
Total # of Tweets added:  528155
Total # of Tweets added:  528655
Total # of Tweets added:  529155
Total # of Tweets added:  529654
Total # of Tweets added:  530154
Total # of Tweets added:  530651
Total # of Tweets added:  531148
Total # of Tweets added:  531647
Total # of Tweets added:  532147
Total # of Tweets added:  532644
Total # of Tweets added:  533144
Total # of Tweets added:  533644
Total # of Tweets added:  534144
Total # of Tweets added:  534644
Total # of Tweets added:  535144
Total # of Tweets added:  535643
Total # of Tweets added:  536142
Total # of Tweets added:  536642
Total # of Tweets added:  537141
Total # of Tweets added:  537638
Total # of Tweets added:  538138
Total # of Tweets added:  538637
Total # of Tweets added:  539136
Total # of Tweets added:  539636
Total # of Tweets added:  540136
Total # of Tweets added:  540636
Total # of Tweets added:  541132
Total # of Tweets added:  541630
Total # of Tweets added:  542125
Total # of Tweets added:  542611
Total # of Tweets added:  543107
Total # of Tweets added:  543604
Total # of Tweets added:  544098
Total # of Tweets added:  544596
Total # of Tweets added:  545089
Total # of Tweets added:  545588
Total # of Tweets added:  546083
Total # of Tweets added:  546576
Total # of Tweets added:  547059
Total # of Tweets added:  547554
Total # of Tweets added:  548049
Total # of Tweets added:  548547
Total # of Tweets added:  549046
Total # of Tweets added:  549534
Total # of Tweets added:  550029
Total # of Tweets added:  550508
Total # of Tweets added:  551002
Total # of Tweets added:  551498
Total # of Tweets added:  551996
Total # of Tweets added:  552490
Total # of Tweets added:  552984
Total # of Tweets added:  553483
Total # of Tweets added:  553981
Total # of Tweets added:  554481
Total # of Tweets added:  554976
Total # of Tweets added:  555473
Total # of Tweets added:  555966
Total # of Tweets added:  556462
Total # of Tweets added:  556954
Total # of Tweets added:  557453
Total # of Tweets added:  557950
Total # of Tweets added:  558444
Total # of Tweets added:  558939
Total # of Tweets added:  559433
Total # of Tweets added:  559932
Total # of Tweets added:  560426
Total # of Tweets added:  560919
Total # of Tweets added:  561416
Total # of Tweets added:  561906
Total # of Tweets added:  562400
Total # of Tweets added:  562896
Total # of Tweets added:  563388
Total # of Tweets added:  563882
Total # of Tweets added:  564377
Total # of Tweets added:  564870
Total # of Tweets added:  565365
Total # of Tweets added:  565861
Total # of Tweets added:  566354
Total # of Tweets added:  566848
Total # of Tweets added:  567346
Total # of Tweets added:  567836
Total # of Tweets added:  568332
Total # of Tweets added:  568829
Total # of Tweets added:  569322
Total # of Tweets added:  569813
Total # of Tweets added:  570305
Total # of Tweets added:  570799
Total # of Tweets added:  571295
Total # of Tweets added:  571792
Total # of Tweets added:  572287
Total # of Tweets added:  572783
Total # of Tweets added:  573280
Total # of Tweets added:  573768
Total # of Tweets added:  574259
Total # of Tweets added:  574748
Total # of Tweets added:  575243
Total # of Tweets added:  575738
Total # of Tweets added:  576234
Total # of Tweets added:  576727
Total # of Tweets added:  577222
Total # of Tweets added:  577716
Total # of Tweets added:  578210
Total # of Tweets added:  578703
Total # of Tweets added:  579196
Total # of Tweets added:  579694
Total # of Tweets added:  580189
Total # of Tweets added:  580682
Total # of Tweets added:  581181
Total # of Tweets added:  581671
Total # of Tweets added:  582165
Total # of Tweets added:  582659
Total # of Tweets added:  583146
Total # of Tweets added:  583638
Total # of Tweets added:  584130
Total # of Tweets added:  584617
Total # of Tweets added:  585114
Total # of Tweets added:  585609
Total # of Tweets added:  586107
Total # of Tweets added:  586599
Total # of Tweets added:  587093
Total # of Tweets added:  587588
Total # of Tweets added:  588081
Total # of Tweets added:  588575
Total # of Tweets added:  589071
Total # of Tweets added:  589564
Total # of Tweets added:  590058
Total # of Tweets added:  590555
Total # of Tweets added:  591051
Total # of Tweets added:  591546
Total # of Tweets added:  592040
Total # of Tweets added:  592536
Total # of Tweets added:  593032
Total # of Tweets added:  593529
Total # of Tweets added:  594025
Total # of Tweets added:  594522
Total # of Tweets added:  595021
Total # of Tweets added:  595519
Total # of Tweets added:  596013
Total # of Tweets added:  596505
Total # of Tweets added:  596999
Total # of Tweets added:  597489
Total # of Tweets added:  597986
Total # of Tweets added:  598479
Total # of Tweets added:  598972
Total # of Tweets added:  599470
Total # of Tweets added:  599960
Total # of Tweets added:  600457
Total # of Tweets added:  600952
Total # of Tweets added:  601441
Total # of Tweets added:  601933
Total # of Tweets added:  602419
Total # of Tweets added:  602910
Total # of Tweets added:  603406
Total # of Tweets added:  603902
Total # of Tweets added:  604397
Total # of Tweets added:  604892
Total # of Tweets added:  605390
Total # of Tweets added:  605883
Total # of Tweets added:  606381
Total # of Tweets added:  606874
Total # of Tweets added:  607372
Total # of Tweets added:  607870
Total # of Tweets added:  608355
Total # of Tweets added:  608851
Total # of Tweets added:  609347
Total # of Tweets added:  609841
Total # of Tweets added:  610333
Total # of Tweets added:  610830
Total # of Tweets added:  611317
Total # of Tweets added:  611816
Total # of Tweets added:  612308
Total # of Tweets added:  612807
Total # of Tweets added:  613303
Total # of Tweets added:  613795
Total # of Tweets added:  614279
Total # of Tweets added:  614762
Total # of Tweets added:  615247
Total # of Tweets added:  615734
Total # of Tweets added:  616232
Total # of Tweets added:  616728
Total # of Tweets added:  617220
Total # of Tweets added:  617716
Total # of Tweets added:  618210
Total # of Tweets added:  618709
Total # of Tweets added:  619202
Total # of Tweets added:  619695
Total # of Tweets added:  620187
Total # of Tweets added:  620685
Total # of Tweets added:  621175
Total # of Tweets added:  621669
Total # of Tweets added:  622162

Total # of Tweets added:  622658
Total # of Tweets added:  623153
Total # of Tweets added:  623649
Total # of Tweets added:  624147
Total # of Tweets added:  624643
Total # of Tweets added:  625140
Total # of Tweets added:  625629
Total # of Tweets added:  626128
Total # of Tweets added:  626625
Total # of Tweets added:  627123
Total # of Tweets added:  627621
Total # of Tweets added:  628115
Total # of Tweets added:  628613
Total # of Tweets added:  629113
Total # of Tweets added:  629613
Total # of Tweets added:  630111
Total # of Tweets added:  630610
Total # of Tweets added:  631109
Total # of Tweets added:  631606
Total # of Tweets added:  632106
Total # of Tweets added:  632604
Total # of Tweets added:  633103
Total # of Tweets added:  633601
Total # of Tweets added:  634101
Total # of Tweets added:  634599
Total # of Tweets added:  635098
Total # of Tweets added:  635596
Total # of Tweets added:  636093
Total # of Tweets added:  636590
Total # of Tweets added:  637088
Total # of Tweets added:  637586
Total # of Tweets added:  638084
Total # of Tweets added:  638584
Total # of Tweets added:  639082
Total # of Tweets added:  639578
Total # of Tweets added:  640074
Total # of Tweets added:  640570
Total # of Tweets added:  641069
Total # of Tweets added:  641566
Total # of Tweets added:  642061
Total # of Tweets added:  642556
Total # of Tweets added:  643054
Total # of Tweets added:  643554
Total # of Tweets added:  644054
Total # of Tweets added:  644554
Total # of Tweets added:  645054
Total # of Tweets added:  645552
Total # of Tweets added:  646047
Total # of Tweets added:  646543
Total # of Tweets added:  647041
Total # of Tweets added:  647540
Total # of Tweets added:  648038
Total # of Tweets added:  648538
Total # of Tweets added:  649038
Total # of Tweets added:  649536
Total # of Tweets added:  650029
Total # of Tweets added:  650527
Total # of Tweets added:  651024
Total # of Tweets added:  651522
Total # of Tweets added:  652020
Total # of Tweets added:  652520
Total # of Tweets added:  653018
Total # of Tweets added:  653517
Total # of Tweets added:  653978
Total # of Tweets added:  654466
Total # of Tweets added:  654963
Total # of Tweets added:  655454
Total # of Tweets added:  655953
Total # of Tweets added:  656452
Total # of Tweets added:  656947
Total # of Tweets added:  657445
Total # of Tweets added:  657943
Total # of Tweets added:  658442
Total # of Tweets added:  658940
Total # of Tweets added:  659438
Total # of Tweets added:  659930
Total # of Tweets added:  660419
Total # of Tweets added:  660914
Total # of Tweets added:  661410
Total # of Tweets added:  661907
Total # of Tweets added:  662406
Total # of Tweets added:  662904
Total # of Tweets added:  663404
Total # of Tweets added:  663901
Total # of Tweets added:  664399
Total # of Tweets added:  664898
Total # of Tweets added:  665396
Total # of Tweets added:  665896
Total # of Tweets added:  666394
Total # of Tweets added:  666892
Total # of Tweets added:  667391
Total # of Tweets added:  667889
Total # of Tweets added:  668386
Total # of Tweets added:  668884
Total # of Tweets added:  669380
Total # of Tweets added:  669878
Total # of Tweets added:  670377
Total # of Tweets added:  670876
Total # of Tweets added:  671373
Total # of Tweets added:  671873
Total # of Tweets added:  672372
Total # of Tweets added:  672871
Total # of Tweets added:  673370
Total # of Tweets added:  673870
Total # of Tweets added:  674367
Total # of Tweets added:  674864
Total # of Tweets added:  675364
Total # of Tweets added:  675863
Total # of Tweets added:  676358
Total # of Tweets added:  676854
Total # of Tweets added:  677352
Total # of Tweets added:  677851
Total # of Tweets added:  678351
Total # of Tweets added:  678850
Total # of Tweets added:  679349
Total # of Tweets added:  679847
Total # of Tweets added:  680344
Total # of Tweets added:  680844
Total # of Tweets added:  681341
Total # of Tweets added:  681840
Total # of Tweets added:  682339
Total # of Tweets added:  682836
Total # of Tweets added:  683329
Total # of Tweets added:  683827
Total # of Tweets added:  684326
Total # of Tweets added:  684823
Total # of Tweets added:  685320
Total # of Tweets added:  685816
Total # of Tweets added:  686315
Total # of Tweets added:  686812
Total # of Tweets added:  687310
Total # of Tweets added:  687807
Total # of Tweets added:  688306
Total # of Tweets added:  688805
Total # of Tweets added:  689301
Total # of Tweets added:  689796
Total # of Tweets added:  690295
Total # of Tweets added:  690794
Total # of Tweets added:  691288
Total # of Tweets added:  691784
Total # of Tweets added:  692284
Total # of Tweets added:  692782
Total # of Tweets added:  693279
Total # of Tweets added:  693777
Total # of Tweets added:  694272
Total # of Tweets added:  694772
Total # of Tweets added:  695268
Total # of Tweets added:  695767
Total # of Tweets added:  696265
Total # of Tweets added:  696764
Total # of Tweets added:  697263
Total # of Tweets added:  697762
Total # of Tweets added:  698257
Total # of Tweets added:  698757
Total # of Tweets added:  699254
Total # of Tweets added:  699751
Total # of Tweets added:  700245
Total # of Tweets added:  700743
Total # of Tweets added:  701242
Total # of Tweets added:  701739
Total # of Tweets added:  702238
Total # of Tweets added:  702736
Total # of Tweets added:  703233
Total # of Tweets added:  703728
Total # of Tweets added:  704225
Total # of Tweets added:  704723
Total # of Tweets added:  705222
Total # of Tweets added:  705718
Total # of Tweets added:  706216
Total # of Tweets added:  706711
Total # of Tweets added:  707209
Total # of Tweets added:  707706
Total # of Tweets added:  708205
Total # of Tweets added:  708411
Total tweets stored:  708411

In [ ]:
csvFile.close()

* 1: Total # of Tweets added:  187365 \
Exception: (429, '{"title":"Too Many Requests","detail":"Too Many Requests","type":"about:blank","status":429}')

* 2: (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f023b491430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
* 3: interrupted
* 4: same as 2 (45271 tweets)
* 5: interrupt

In [ ]:
df = pd.read_csv('tweetsSDG_en.csv')
display(df.head())

,twid,authid,created_at,lang,like_count,quote_count,reply_count,retweet_count,text
0,1498444897636036608,2875796095,2022-02-28 23:47:58+00:00,en,8,0,1,14,@HakomTimeSeries @thenextweb @Analytics_699 @j...
1,1498442516676624387,981318439154282497,2022-02-28 23:38:30+00:00,en,0,0,0,0,#ModelShave Waist length red hair lady becomes...
2,1498442347905892358,986793528394104832,2022-02-28 23:37:50+00:00,en,3,0,0,1,#PNG #DigitalTransformation - NEW course to l...
3,1498442248953946112,1443986304178475012,2022-02-28 23:37:26+00:00,en,2,0,0,0,It also calls for the full participation of wo...
4,1498442101729775618,1443986304178475012,2022-02-28 23:36:51+00:00,en,2,0,1,0,SDG 5 aims to achieve gender equality by endin...

In [ ]:
display(df.tail())
df.info()

,twid,authid,created_at,lang,like_count,quote_count,reply_count,retweet_count,text
187335,1371793809038848005,1154381411614416906,2021-03-16 12:01:45+00:00,en,1,0,0,0,Help me plant a forest. Sign up for my #TechWi...
187336,1371793676721139713,1141826418822848512,2021-03-16 12:01:13+00:00,en,1,0,0,0,Great news 🙌 We are in partnership with\nImpac...
187337,1371793494608650244,202313343,2021-03-16 12:00:30+00:00,en,7,0,0,1,The only way to meet the Paris Agreement goals...
187338,1371793371405066250,90561618,2021-03-16 12:00:01+00:00,en,0,0,0,0,Let’s Talk EduClowns! Did you know they've per...
187339,1371793203062398983,747357300638158848,2021-03-16 11:59:20+00:00,en,0,0,0,0,@SustInsti @GlobeScan It would be interesting ...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187340 entries, 0 to 187339
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   twid           187340 non-null  int64
 1   authid         187340 non-null  int64
 2   created_at     187340 non-null  object
 3   lang           187340 non-null  object
 4   like_count     187340 non-null  int64
 5   quote_count    187340 non-null  int64
 6   reply_count    187340 non-null  int64
 7   retweet_count  187340 non-null  int64
 8   text           187340 non-null  object
dtypes: int64(6), object(3)
memory usage: 12.9+ MB

In [ ]:
# test to retrieve data
print(json_response['data'][0]['created_at']) #tweets are printed from newest to oldest, so [0] is the most recent
print(json_response['data'][-1]['created_at'])
#print(json_response['data'][0])

#test to retrieve metadata
print(json_response['meta']['result_count'])
#print(json_response['meta'])

2022-02-18T13:18:51.000Z
2022-02-18T13:17:28.000Z
15